server:
  servlet:
    port: 8080
    context-path: /fxrates

jasypt:
  encryptor:
    password: martrustAssessment
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

fxrates:
  # Hosted API for https://exchangeratesapi.io/
  # https://apilayer.com/marketplace/exchangerates_data-api?preview=true#documentation-tab
  # Access key provided by ApiLayer
  baseUrl: https://api.apilayer.com/exchangerates_data/
  apiKey: ENC(ozNsxXdJIGPKsM8ggntsEiP98QHsoOT67cmEz+poiwHfaLcdIG4yMiM7k8FUhaDm)